"""Mise à jour des tables de données.

Revision ID: 248daa358ae9
Revises: 
Create Date: 2024-06-18 19:48:57.324117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248daa358ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biography_mangaka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography_content', sa.Text(), nullable=False),
    sa.Column('date_bio_mangaka', sa.DateTime(), nullable=False),
    sa.Column('mangaka_name', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_biography', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'biography_mangaka', ['biography_mangaka_id'], ['id'])

    with op.batch_alter_table('dislikes_biography', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'biography_mangaka', ['biography_mangaka_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('likes_biography', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'biography_mangaka', ['biography_mangaka_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profil_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('likes_biography', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dislikes_biography', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comment_biography', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('biography_mangaka')
    # ### end Alembic commands ###
