"""empty message

Revision ID: 29692d3fa370
Revises: ebb15317076d
Create Date: 2024-06-19 19:39:09.710624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29692d3fa370'
down_revision = 'ebb15317076d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_photo', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('chemin_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chemin_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('profil_photo')

    # ### end Alembic commands ###
