"""Migration initiale

Revision ID: de21b5638b60
Revises: 
Create Date: 2024-06-10 19:15:24.769776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de21b5638b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biography_mangaka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography_content', sa.Text(), nullable=False),
    sa.Column('date_bio_mangaka', sa.DateTime(), nullable=False),
    sa.Column('mangaka_name', sa.String(length=50), nullable=False),
    sa.Column('pseudo_author', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['pseudo_author'], ['author.pseudo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('article_pseudo_author_fkey', type_='foreignkey')
        batch_op.drop_column('pseudo_author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pseudo_author', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('article_pseudo_author_fkey', 'author', ['pseudo_author'], ['pseudo'])

    op.drop_table('biography_mangaka')
    # ### end Alembic commands ###
