"""empty message

Revision ID: ebb15317076d
Revises: 248daa358ae9
Create Date: 2024-06-19 19:03:25.709428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb15317076d'
down_revision = '248daa358ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chemin_photo', sa.String(length=255), nullable=False))
        batch_op.drop_column('profil_photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('chemin_photo')

    # ### end Alembic commands ###
